name:                automata
version:             0.1.0.0
github:              "leohaskell/automata"
license:             MIT
author:              "Daniel Taskoff"
maintainer:          "daniel.taskoff@gmail.com"
copyright:           "2018 Daniel Taskoff"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/automata#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  automata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - automata

tests:
  fst-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - automata
